spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: gateway-server
    description: Gateway Server
    version: 1.0.0

logging:
  level:
    learn:
      microservices:
        gatewayserver: DEBUG
