services:
  rabbitmq:
    image: "rabbitmq:3.13.4-management"
    container_name: rabbitmq
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - bank-loan

  accounts-db:
    image: postgres
    container_name: accountsdb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: accountsdb
    networks:
      - accounts-db

  cards-db:
    image: postgres
    container_name: cardsdb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cardsdb
    networks:
      - cards-db

  loans-db:
    image: postgres
    container_name: loansdb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: loansdb
    networks:
      - loans-db


  config-server:
    image: "helmyl/config-server"
    container_name: config-server
    ports:
      - "8071:8071"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - bank-loan
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"

  eureka-server:
    image: "helmyl/eureka-server"
    container_name: eureka-server
    ports:
      - "8070:8070"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      SPRING_RABBITMQ_HOST: "rabbitmq"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - bank-loan


  cards:
    image: "helmyl/cards-ms"
    container_name: cards-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_DATASOURCE_URL: jdbc:postgresql://cards-db:5432/cardsdb
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
    networks:
      - bank-loan
      - cards-db

  loans:
    image: "helmyl/loans-ms"
    container_name: loans-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_DATASOURCE_URL: jdbc:postgresql://loans-db:5432/loansdb
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
    networks:
      - bank-loan
      - loans-db

  accounts:
    image: "helmyl/accounts-ms"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      cards:
        condition: service_started
      loans:
        condition: service_started
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      SPRING_RABBITMQ_HOST: "rabbitmq"
      SPRING_DATASOURCE_URL: jdbc:postgresql://accounts-db:5432/accountsdb
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
    networks:
      - bank-loan
      - accounts-db
      - cards-db
      - loans-db

  gateway-server:
    image: "helmyl/gateway-server"
    container_name: gateway-server
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_started
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/
      SPRING_RABBITMQ_HOST: "rabbitmq"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
    networks:
      - bank-loan
      - accounts-db
      - cards-db
      - loans-db

networks:
  bank-loan:
    driver: bridge
  accounts-db:
    driver: bridge
  cards-db:
    driver: bridge
  loans-db:
    driver: bridge
