server:
  port: 8090

spring:
  application:
    name: loans

  datasource:
    url: jdbc:postgresql://localhost:5434/loansdb
    driver-class-name: org.postgresql.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always
  
  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    kubernetes:
      discovery:
        all-namespaces: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

  endpoint:
    shutdown:
      enabled: true

  info:
    env:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: cards
    description: "Cards Service"
    version: "0.0.1-3b"

logging:
  level:
    learn:
      microservices:
        cards: DEBUG

  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"